variables:
  PACKAGE_HAS_LIBRARIES: "true"
  PACKAGE_HAS_TESTS: "true"
  PACKAGE_HAS_EXAMPLES: "false"
  PACKAGE_HAS_SITE: "false"
  PACKAGE_BINARIES_PUBLISHED: "false"
  PACKAGE_DEV_INFO_PUBLISHED: "false"

cache:
  key: "$CI_BUILD_REF/$CI_BUILD_REF_NAME"
  paths:
   - binaries/
   - build/

stages:
 - configure
 - build
 - deploy
 - cleanup

############ patterns for in job description #############

# Hidden key that defines an anchor for reusing artifacts def
.artifacts_integration_:
    artifacts: &artifacts_integration
        name: "artefacts_${CI_BUILD_REF_NAME}"
        paths:
          - build/release/share/developper_info.tgz

.artifacts_release_:
    artifacts: &artifacts_release
        name: "artefacts_${CI_BUILD_REF_NAME}"
        paths:
          - build/release/share/dependencies.txt

# Hidden key that defines an anchor for reusing artifacts uploaded when a build fails
.artifacts_when_failing_:
    artifacts: &artifacts_on_failure
        name: "artefacts_${CI_BUILD_REF_NAME}"
        paths:
          - build/release/share/dependencies.txt
        when: on_failure

# Hidden key that defines an anchor for reusing code relative to integration branch
.selection_integration_: &job_selection_integration
    only:
        - integration

# Hidden key that defines an anchor for reusing code relative to released versions
.selection_release_: &job_selection_release
    only:
         - tags
         - /^v.*$/

.build_any_: &build_job
    stage: build
    script:
      - chmod 700 ./share/ci/build_package.sh
      - ./share/ci/build_package.sh

.cleanup_any_: &cleanup_job
   stage: cleanup
   script:
     - chmod 700 ./share/ci/cleanup_package.sh
     - ./share/ci/cleanup_package.sh
   when: always

############ generic jobs patterns #############

### configure (CMake project configuration)
.configure_integration_: &configure_integration
    stage: configure
    script:
         - chmod 700 ./share/ci/prepare_package_ci.sh
         - ./share/ci/prepare_package_ci.sh
         - chmod 700 ./share/ci/configure_package_integration.sh
         - ./share/ci/configure_package_integration.sh
    <<: *job_selection_integration

.configure_release_: &configure_release
    stage: configure
    script:
         - chmod 700 ./share/ci/prepare_package_ci.sh
         - ./share/ci/prepare_package_ci.sh
         - chmod 700 ./share/ci/configure_package_release.sh
         - ./share/ci/configure_package_release.sh
    <<: *job_selection_release

### build

.build_integration_: &build_integration
    <<: *build_job
    artifacts: *artifacts_on_failure
    <<: *job_selection_integration

.build_release_: &build_release
    <<: *build_job
    artifacts: *artifacts_on_failure
    <<: *job_selection_release


### deploy (make interesting part of the result available wiki+doc, binaries)

.deploy_integration_: &deploy_integration
    stage: deploy
    script:
         - chmod 700 ./share/ci/deploy_package_integration.sh
         - ./share/ci/deploy_package_integration.sh
    artifacts: *artifacts_integration
    <<: *job_selection_integration

.deploy_release_: &deploy_release
    stage: deploy
    script:
         - chmod 700 ./share/ci/deploy_package_release.sh
         - ./share/ci/deploy_package_release.sh
    artifacts: *artifacts_release
    <<: *job_selection_release

### cleanup when pipeline is finished

.cleanup_integration_: &cleanup_integration
  <<: *cleanup_job
  <<: *job_selection_integration

.cleanup_release_: &cleanup_release
  <<: *cleanup_job
  <<: *job_selection_release

############ patterns for platforms selection #############
# here the project generates patterns for runner selection according for all platforms defined in the workspace
#platform x86_32_linux_abi98

.selection_platform_x86_32_linux_abi98_: &selection_platform_x86_32_linux_abi98
    tags:
        - pid
        - x86_32_linux_abi98

#platform x86_64_xenomai_abi11

.selection_platform_x86_64_xenomai_abi11_: &selection_platform_x86_64_xenomai_abi11
    tags:
        - pid
        - x86_64_xenomai_abi11

#platform x86_64_linux_abi98

.selection_platform_x86_64_linux_abi98_: &selection_platform_x86_64_linux_abi98
    tags:
        - pid
        - x86_64_linux_abi98

#platform x86_64_macosx_abi11

.selection_platform_x86_64_macosx_abi11_: &selection_platform_x86_64_macosx_abi11
    tags:
        - pid
        - x86_64_macosx_abi11

#platform x86_64_macosx_abi98

.selection_platform_x86_64_macosx_abi98_: &selection_platform_x86_64_macosx_abi98
    tags:
        - pid
        - x86_64_macosx_abi98

#platform x86_32_xenomai_abi98

.selection_platform_x86_32_xenomai_abi98_: &selection_platform_x86_32_xenomai_abi98
    tags:
        - pid
        - x86_32_xenomai_abi98

#platform arm_32_linux_abi98

.selection_platform_arm_32_linux_abi98_: &selection_platform_arm_32_linux_abi98
    tags:
        - pid
        - arm_32_linux_abi98

#platform arm_32_abi11

.selection_platform_arm_32_abi11_: &selection_platform_arm_32_abi11
    tags:
        - pid
        - arm_32_abi11

#platform x86_32_linux_abi11

.selection_platform_x86_32_linux_abi11_: &selection_platform_x86_32_linux_abi11
    tags:
        - pid
        - x86_32_linux_abi11

#platform x86_64_linux_abi11

.selection_platform_x86_64_linux_abi11_: &selection_platform_x86_64_linux_abi11
    tags:
        - pid
        - x86_64_linux_abi11



############ jobs definition, by platform #############

#pipeline generated for platform: x86_32_linux_abi98

#integration jobs for platform x86_32_linux_abi98

configure_integration_x86_32_linux_abi98:
  <<: *configure_integration
  <<: *selection_platform_x86_32_linux_abi98

build_integration_x86_32_linux_abi98:
  <<: *build_integration
  <<: *selection_platform_x86_32_linux_abi98

deploy_integration_x86_32_linux_abi98:
  <<: *deploy_integration
  <<: *selection_platform_x86_32_linux_abi98

cleanup_integration_x86_32_linux_abi98:
  <<: *cleanup_integration
  <<: *selection_platform_x86_32_linux_abi98

#release jobs for platform x86_32_linux_abi98

configure_release_x86_32_linux_abi98:
  <<: *configure_release
  <<: *selection_platform_x86_32_linux_abi98

build_release_x86_32_linux_abi98:
  <<: *build_release
  <<: *selection_platform_x86_32_linux_abi98

deploy_release_x86_32_linux_abi98:
  <<: *deploy_release
  <<: *selection_platform_x86_32_linux_abi98

cleanup_release_x86_32_linux_abi98:
  <<: *cleanup_release
  <<: *selection_platform_x86_32_linux_abi98

#pipeline generated for platform: x86_64_xenomai_abi11

#integration jobs for platform x86_64_xenomai_abi11

configure_integration_x86_64_xenomai_abi11:
  <<: *configure_integration
  <<: *selection_platform_x86_64_xenomai_abi11

build_integration_x86_64_xenomai_abi11:
  <<: *build_integration
  <<: *selection_platform_x86_64_xenomai_abi11

deploy_integration_x86_64_xenomai_abi11:
  <<: *deploy_integration
  <<: *selection_platform_x86_64_xenomai_abi11

cleanup_integration_x86_64_xenomai_abi11:
  <<: *cleanup_integration
  <<: *selection_platform_x86_64_xenomai_abi11

#release jobs for platform x86_64_xenomai_abi11

configure_release_x86_64_xenomai_abi11:
  <<: *configure_release
  <<: *selection_platform_x86_64_xenomai_abi11

build_release_x86_64_xenomai_abi11:
  <<: *build_release
  <<: *selection_platform_x86_64_xenomai_abi11

deploy_release_x86_64_xenomai_abi11:
  <<: *deploy_release
  <<: *selection_platform_x86_64_xenomai_abi11

cleanup_release_x86_64_xenomai_abi11:
  <<: *cleanup_release
  <<: *selection_platform_x86_64_xenomai_abi11

#pipeline generated for platform: x86_64_linux_abi98

#integration jobs for platform x86_64_linux_abi98

configure_integration_x86_64_linux_abi98:
  <<: *configure_integration
  <<: *selection_platform_x86_64_linux_abi98

build_integration_x86_64_linux_abi98:
  <<: *build_integration
  <<: *selection_platform_x86_64_linux_abi98

deploy_integration_x86_64_linux_abi98:
  <<: *deploy_integration
  <<: *selection_platform_x86_64_linux_abi98

cleanup_integration_x86_64_linux_abi98:
  <<: *cleanup_integration
  <<: *selection_platform_x86_64_linux_abi98

#release jobs for platform x86_64_linux_abi98

configure_release_x86_64_linux_abi98:
  <<: *configure_release
  <<: *selection_platform_x86_64_linux_abi98

build_release_x86_64_linux_abi98:
  <<: *build_release
  <<: *selection_platform_x86_64_linux_abi98

deploy_release_x86_64_linux_abi98:
  <<: *deploy_release
  <<: *selection_platform_x86_64_linux_abi98

cleanup_release_x86_64_linux_abi98:
  <<: *cleanup_release
  <<: *selection_platform_x86_64_linux_abi98

#pipeline generated for platform: x86_64_macosx_abi11

#integration jobs for platform x86_64_macosx_abi11

configure_integration_x86_64_macosx_abi11:
  <<: *configure_integration
  <<: *selection_platform_x86_64_macosx_abi11

build_integration_x86_64_macosx_abi11:
  <<: *build_integration
  <<: *selection_platform_x86_64_macosx_abi11

deploy_integration_x86_64_macosx_abi11:
  <<: *deploy_integration
  <<: *selection_platform_x86_64_macosx_abi11

cleanup_integration_x86_64_macosx_abi11:
  <<: *cleanup_integration
  <<: *selection_platform_x86_64_macosx_abi11

#release jobs for platform x86_64_macosx_abi11

configure_release_x86_64_macosx_abi11:
  <<: *configure_release
  <<: *selection_platform_x86_64_macosx_abi11

build_release_x86_64_macosx_abi11:
  <<: *build_release
  <<: *selection_platform_x86_64_macosx_abi11

deploy_release_x86_64_macosx_abi11:
  <<: *deploy_release
  <<: *selection_platform_x86_64_macosx_abi11

cleanup_release_x86_64_macosx_abi11:
  <<: *cleanup_release
  <<: *selection_platform_x86_64_macosx_abi11

#pipeline generated for platform: x86_64_macosx_abi98

#integration jobs for platform x86_64_macosx_abi98

configure_integration_x86_64_macosx_abi98:
  <<: *configure_integration
  <<: *selection_platform_x86_64_macosx_abi98

build_integration_x86_64_macosx_abi98:
  <<: *build_integration
  <<: *selection_platform_x86_64_macosx_abi98

deploy_integration_x86_64_macosx_abi98:
  <<: *deploy_integration
  <<: *selection_platform_x86_64_macosx_abi98

cleanup_integration_x86_64_macosx_abi98:
  <<: *cleanup_integration
  <<: *selection_platform_x86_64_macosx_abi98

#release jobs for platform x86_64_macosx_abi98

configure_release_x86_64_macosx_abi98:
  <<: *configure_release
  <<: *selection_platform_x86_64_macosx_abi98

build_release_x86_64_macosx_abi98:
  <<: *build_release
  <<: *selection_platform_x86_64_macosx_abi98

deploy_release_x86_64_macosx_abi98:
  <<: *deploy_release
  <<: *selection_platform_x86_64_macosx_abi98

cleanup_release_x86_64_macosx_abi98:
  <<: *cleanup_release
  <<: *selection_platform_x86_64_macosx_abi98

#pipeline generated for platform: x86_32_xenomai_abi98

#integration jobs for platform x86_32_xenomai_abi98

configure_integration_x86_32_xenomai_abi98:
  <<: *configure_integration
  <<: *selection_platform_x86_32_xenomai_abi98

build_integration_x86_32_xenomai_abi98:
  <<: *build_integration
  <<: *selection_platform_x86_32_xenomai_abi98

deploy_integration_x86_32_xenomai_abi98:
  <<: *deploy_integration
  <<: *selection_platform_x86_32_xenomai_abi98

cleanup_integration_x86_32_xenomai_abi98:
  <<: *cleanup_integration
  <<: *selection_platform_x86_32_xenomai_abi98

#release jobs for platform x86_32_xenomai_abi98

configure_release_x86_32_xenomai_abi98:
  <<: *configure_release
  <<: *selection_platform_x86_32_xenomai_abi98

build_release_x86_32_xenomai_abi98:
  <<: *build_release
  <<: *selection_platform_x86_32_xenomai_abi98

deploy_release_x86_32_xenomai_abi98:
  <<: *deploy_release
  <<: *selection_platform_x86_32_xenomai_abi98

cleanup_release_x86_32_xenomai_abi98:
  <<: *cleanup_release
  <<: *selection_platform_x86_32_xenomai_abi98

#pipeline generated for platform: arm_32_linux_abi98

#integration jobs for platform arm_32_linux_abi98

configure_integration_arm_32_linux_abi98:
  <<: *configure_integration
  <<: *selection_platform_arm_32_linux_abi98

build_integration_arm_32_linux_abi98:
  <<: *build_integration
  <<: *selection_platform_arm_32_linux_abi98

deploy_integration_arm_32_linux_abi98:
  <<: *deploy_integration
  <<: *selection_platform_arm_32_linux_abi98

cleanup_integration_arm_32_linux_abi98:
  <<: *cleanup_integration
  <<: *selection_platform_arm_32_linux_abi98

#release jobs for platform arm_32_linux_abi98

configure_release_arm_32_linux_abi98:
  <<: *configure_release
  <<: *selection_platform_arm_32_linux_abi98

build_release_arm_32_linux_abi98:
  <<: *build_release
  <<: *selection_platform_arm_32_linux_abi98

deploy_release_arm_32_linux_abi98:
  <<: *deploy_release
  <<: *selection_platform_arm_32_linux_abi98

cleanup_release_arm_32_linux_abi98:
  <<: *cleanup_release
  <<: *selection_platform_arm_32_linux_abi98

#pipeline generated for platform: arm_32_abi11

#integration jobs for platform arm_32_abi11

configure_integration_arm_32_abi11:
  <<: *configure_integration
  <<: *selection_platform_arm_32_abi11

build_integration_arm_32_abi11:
  <<: *build_integration
  <<: *selection_platform_arm_32_abi11

deploy_integration_arm_32_abi11:
  <<: *deploy_integration
  <<: *selection_platform_arm_32_abi11

cleanup_integration_arm_32_abi11:
  <<: *cleanup_integration
  <<: *selection_platform_arm_32_abi11

#release jobs for platform arm_32_abi11

configure_release_arm_32_abi11:
  <<: *configure_release
  <<: *selection_platform_arm_32_abi11

build_release_arm_32_abi11:
  <<: *build_release
  <<: *selection_platform_arm_32_abi11

deploy_release_arm_32_abi11:
  <<: *deploy_release
  <<: *selection_platform_arm_32_abi11

cleanup_release_arm_32_abi11:
  <<: *cleanup_release
  <<: *selection_platform_arm_32_abi11

#pipeline generated for platform: x86_32_linux_abi11

#integration jobs for platform x86_32_linux_abi11

configure_integration_x86_32_linux_abi11:
  <<: *configure_integration
  <<: *selection_platform_x86_32_linux_abi11

build_integration_x86_32_linux_abi11:
  <<: *build_integration
  <<: *selection_platform_x86_32_linux_abi11

deploy_integration_x86_32_linux_abi11:
  <<: *deploy_integration
  <<: *selection_platform_x86_32_linux_abi11

cleanup_integration_x86_32_linux_abi11:
  <<: *cleanup_integration
  <<: *selection_platform_x86_32_linux_abi11

#release jobs for platform x86_32_linux_abi11

configure_release_x86_32_linux_abi11:
  <<: *configure_release
  <<: *selection_platform_x86_32_linux_abi11

build_release_x86_32_linux_abi11:
  <<: *build_release
  <<: *selection_platform_x86_32_linux_abi11

deploy_release_x86_32_linux_abi11:
  <<: *deploy_release
  <<: *selection_platform_x86_32_linux_abi11

cleanup_release_x86_32_linux_abi11:
  <<: *cleanup_release
  <<: *selection_platform_x86_32_linux_abi11

#pipeline generated for platform: x86_64_linux_abi11

#integration jobs for platform x86_64_linux_abi11

configure_integration_x86_64_linux_abi11:
  <<: *configure_integration
  <<: *selection_platform_x86_64_linux_abi11

build_integration_x86_64_linux_abi11:
  <<: *build_integration
  <<: *selection_platform_x86_64_linux_abi11

deploy_integration_x86_64_linux_abi11:
  <<: *deploy_integration
  <<: *selection_platform_x86_64_linux_abi11

cleanup_integration_x86_64_linux_abi11:
  <<: *cleanup_integration
  <<: *selection_platform_x86_64_linux_abi11

#release jobs for platform x86_64_linux_abi11

configure_release_x86_64_linux_abi11:
  <<: *configure_release
  <<: *selection_platform_x86_64_linux_abi11

build_release_x86_64_linux_abi11:
  <<: *build_release
  <<: *selection_platform_x86_64_linux_abi11

deploy_release_x86_64_linux_abi11:
  <<: *deploy_release
  <<: *selection_platform_x86_64_linux_abi11

cleanup_release_x86_64_linux_abi11:
  <<: *cleanup_release
  <<: *selection_platform_x86_64_linux_abi11

